services:
  nextjs:
    image: nextjs:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/ssl:ro
    restart: always
  fastapi:
    image: fastapi:latest
    container_name: fastapi
    volumes:
      - /srv/data:/srv/data
    ports:
      - "8081:80"
    restart: always
