---
name: Docker deployment

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build NextJS Docker image
        run: docker build -t nextjs:latest -f Dockerfile.next .

      - name: Build Nginx Docker image
        run: docker build -t nginx:latest -f Dockerfile.nginx .

      - name: Save Docker images
        run: |
          docker save nextjs > nextjs.tar && \
          docker save nginx > nginx.tar

      - name: Copy images to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASS }}
          source: "nextjs.tar,nginx.tar,docker-compose.yml"
          target: /home/${{ secrets.SSH_USER }}/website/

      - name: SSH Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASS }}
          script: |
            cd ~/website/ && \
            (echo "${{ secrets.USER_PASS }}" | sudo -S docker load -i nextjs.tar) && \
            (echo "${{ secrets.USER_PASS }}" | sudo -S docker load -i nginx.tar) && \
            (echo "${{ secrets.USER_PASS }}" | sudo -S docker compose up -d --no-deps)
